/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_kafka_clients_producer_SharedMemoryProducer */

#ifndef _Included_org_apache_kafka_clients_producer_SharedMemoryProducer
#define _Included_org_apache_kafka_clients_producer_SharedMemoryProducer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_kafka_clients_producer_SharedMemoryProducer
 * Method:    allocateSharedMemoryByBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_apache_kafka_clients_producer_SharedMemoryProducer_allocateSharedMemoryByBuffer
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_kafka_clients_producer_SharedMemoryProducer
 * Method:    commitSharedMemoryByBuffer
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_apache_kafka_clients_producer_SharedMemoryProducer_commitSharedMemoryByBuffer
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_apache_kafka_clients_producer_SharedMemoryProducer
 * Method:    readSharedMemoryByBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_apache_kafka_clients_producer_SharedMemoryProducer_readSharedMemoryByBuffer
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_kafka_clients_producer_SharedMemoryProducer
 * Method:    closeSharedMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_kafka_clients_producer_SharedMemoryProducer_closeSharedMemory
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
