/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_kafka_clients_producer_SharedMemoryManager */

#ifndef _Included_org_apache_kafka_clients_producer_SharedMemoryManager
#define _Included_org_apache_kafka_clients_producer_SharedMemoryManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_kafka_clients_producer_SharedMemoryManager
 * Method:    writeSharedMemoryByBuffer
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_apache_kafka_clients_producer_SharedMemoryManager_writeSharedMemoryByBuffer
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_apache_kafka_clients_producer_SharedMemoryManager
 * Method:    readSharedMemoryByBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_apache_kafka_clients_producer_SharedMemoryManager_readSharedMemoryByBuffer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
