/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_kafka_clients_consumer_SharedMemoryConsumer */

#ifndef _Included_org_apache_kafka_clients_consumer_SharedMemoryConsumer
#define _Included_org_apache_kafka_clients_consumer_SharedMemoryConsumer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_kafka_clients_consumer_SharedMemoryConsumer
 * Method:    writeSharedMemoryToServer
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_apache_kafka_clients_consumer_SharedMemoryConsumer_writeSharedMemoryToServer
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_apache_kafka_clients_consumer_SharedMemoryConsumer
 * Method:    writeSharedMemoryByBuffer
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_apache_kafka_clients_consumer_SharedMemoryConsumer_writeSharedMemoryByBuffer
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_apache_kafka_clients_consumer_SharedMemoryConsumer
 * Method:    readSharedMemoryByBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_apache_kafka_clients_consumer_SharedMemoryConsumer_readSharedMemoryByBuffer
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_kafka_clients_consumer_SharedMemoryConsumer
 * Method:    readSharedMemoryByConsumer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_apache_kafka_clients_consumer_SharedMemoryConsumer_readSharedMemoryByConsumer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
