/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_kafka_clients_producer_SharedMemoryProducer */

#ifndef _Included_org_apache_kafka_clients_producer_SharedMemoryProducer
#define _Included_org_apache_kafka_clients_producer_SharedMemoryProducer
#ifdef __cplusplus
extern "C" {
#endif
#undef org_apache_kafka_clients_producer_SharedMemoryProducer_SLOT_SIZE
#define org_apache_kafka_clients_producer_SharedMemoryProducer_SLOT_SIZE 1048576L
/*
 * Class:     org_apache_kafka_clients_producer_SharedMemoryProducer
 * Method:    getPoolBigBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_apache_kafka_clients_producer_SharedMemoryProducer_getPoolBigBuffer
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_kafka_clients_producer_SharedMemoryProducer
 * Method:    allocateSharedMemoryByBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_apache_kafka_clients_producer_SharedMemoryProducer_allocateSharedMemoryByBuffer
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_kafka_clients_producer_SharedMemoryProducer
 * Method:    commitSharedMemoryByBuffer
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_apache_kafka_clients_producer_SharedMemoryProducer_commitSharedMemoryByBuffer
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_apache_kafka_clients_producer_SharedMemoryProducer
 * Method:    readSharedMemoryByBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_apache_kafka_clients_producer_SharedMemoryProducer_readSharedMemoryByBuffer
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_kafka_clients_producer_SharedMemoryProducer
 * Method:    readSharedMemoryByIndex
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_apache_kafka_clients_producer_SharedMemoryProducer_readSharedMemoryByIndex
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_kafka_clients_producer_SharedMemoryProducer
 * Method:    closeSharedMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_kafka_clients_producer_SharedMemoryProducer_closeSharedMemory
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_kafka_clients_producer_SharedMemoryProducer
 * Method:    releaseSharedmemoryByBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_apache_kafka_clients_producer_SharedMemoryProducer_releaseSharedmemoryByBuffer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_apache_kafka_clients_producer_SharedMemoryProducer
 * Method:    allocateSharedMemoryIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_kafka_clients_producer_SharedMemoryProducer_allocateSharedMemoryIndex
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_kafka_clients_producer_SharedMemoryProducer
 * Method:    commitSharedMemoryByIndex
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_apache_kafka_clients_producer_SharedMemoryProducer_commitSharedMemoryByIndex
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_apache_kafka_clients_producer_SharedMemoryProducer
 * Method:    releaseSharedMemoryIndex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_apache_kafka_clients_producer_SharedMemoryProducer_releaseSharedMemoryIndex
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
